[2025-01-06T10:21:26.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T10:21:26.079+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T10:21:10.397834+00:00 [queued]>
[2025-01-06T10:21:26.100+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.load_data manual__2025-01-06T10:21:10.397834+00:00 [queued]>
[2025-01-06T10:21:26.102+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T10:21:26.126+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-06 10:21:10.397834+00:00
[2025-01-06T10:21:26.137+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=250) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T10:21:26.139+0000] {standard_task_runner.py:72} INFO - Started process 251 to run task
[2025-01-06T10:21:26.140+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'load_data', 'manual__2025-01-06T10:21:10.397834+00:00', '--job-id', '791', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmpt68xqu9k']
[2025-01-06T10:21:26.143+0000] {standard_task_runner.py:105} INFO - Job 791: Subtask load_data
[2025-01-06T10:21:26.244+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.load_data manual__2025-01-06T10:21:10.397834+00:00 [running]> on host 4f9b54363226
[2025-01-06T10:21:26.435+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T10:21:10.397834+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T10:21:10.397834+00:00'
[2025-01-06T10:21:26.436+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T10:21:26.470+0000] {base.py:84} INFO - Retrieving connection 'pg_connect'
[2025-01-06T10:21:26.756+0000] {kaggle_dag.py:48} INFO - Данные вставились в БД
[2025-01-06T10:21:26.758+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T10:21:26.773+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T10:21:26.774+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=load_data, run_id=manual__2025-01-06T10:21:10.397834+00:00, execution_date=20250106T102110, start_date=20250106T102126, end_date=20250106T102126
[2025-01-06T10:21:26.840+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T10:21:26.860+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
