[2025-01-06T19:18:34.286+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T19:18:34.327+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.unpack_kaggle_data manual__2025-01-06T19:18:16.983417+00:00 [queued]>
[2025-01-06T19:18:34.346+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.unpack_kaggle_data manual__2025-01-06T19:18:16.983417+00:00 [queued]>
[2025-01-06T19:18:34.348+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T19:18:34.382+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): unpack_kaggle_data> on 2025-01-06 19:18:16.983417+00:00
[2025-01-06T19:18:34.394+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T19:18:34.399+0000] {standard_task_runner.py:72} INFO - Started process 116 to run task
[2025-01-06T19:18:34.399+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'unpack_kaggle_data', 'manual__2025-01-06T19:18:16.983417+00:00', '--job-id', '861', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmp0zt_4nj7']
[2025-01-06T19:18:34.402+0000] {standard_task_runner.py:105} INFO - Job 861: Subtask unpack_kaggle_data
[2025-01-06T19:18:34.501+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.unpack_kaggle_data manual__2025-01-06T19:18:16.983417+00:00 [running]> on host b5c0ace8ab2f
[2025-01-06T19:18:34.689+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='unpack_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T19:18:16.983417+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T19:18:16.983417+00:00'
[2025-01-06T19:18:34.692+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T19:18:34.743+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T19:18:34.762+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T19:18:34.763+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=unpack_kaggle_data, run_id=manual__2025-01-06T19:18:16.983417+00:00, execution_date=20250106T191816, start_date=20250106T191834, end_date=20250106T191834
[2025-01-06T19:18:34.818+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T19:18:34.883+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T19:18:34.888+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
