[2025-01-06T17:36:31.412+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-06T17:36:31.458+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dag.unpack_kaggle_data manual__2025-01-06T17:36:17.082564+00:00 [queued]>
[2025-01-06T17:36:31.478+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dag.unpack_kaggle_data manual__2025-01-06T17:36:17.082564+00:00 [queued]>
[2025-01-06T17:36:31.480+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-06T17:36:31.512+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): unpack_kaggle_data> on 2025-01-06 17:36:17.082564+00:00
[2025-01-06T17:36:31.522+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=109) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-06T17:36:31.525+0000] {standard_task_runner.py:72} INFO - Started process 110 to run task
[2025-01-06T17:36:31.525+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dag', 'unpack_kaggle_data', 'manual__2025-01-06T17:36:17.082564+00:00', '--job-id', '843', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dag.py', '--cfg-path', '/tmp/tmp6h0kb6q8']
[2025-01-06T17:36:31.527+0000] {standard_task_runner.py:105} INFO - Job 843: Subtask unpack_kaggle_data
[2025-01-06T17:36:31.621+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_dag.unpack_kaggle_data manual__2025-01-06T17:36:17.082564+00:00 [running]> on host f560492d2669
[2025-01-06T17:36:31.820+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dag' AIRFLOW_CTX_TASK_ID='unpack_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T17:36:17.082564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T17:36:17.082564+00:00'
[2025-01-06T17:36:31.823+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-06T17:36:31.924+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-06T17:36:31.942+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-06T17:36:31.944+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=kaggle_dag, task_id=unpack_kaggle_data, run_id=manual__2025-01-06T17:36:17.082564+00:00, execution_date=20250106T173617, start_date=20250106T173631, end_date=20250106T173631
[2025-01-06T17:36:31.984+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-06T17:36:32.036+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-06T17:36:32.043+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
